// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hJiUQxc8ii_Z8jGAV6ujAKtvuQR3ay4',
    appId: '1:686258857713:web:46ac6b03695e95f077ab50',
    messagingSenderId: '686258857713',
    projectId: 'hospital-4ad8b',
    authDomain: 'hospital-4ad8b.firebaseapp.com',
    storageBucket: 'hospital-4ad8b.appspot.com',
    measurementId: 'G-6V26PT93E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwg1YFP2N1TsZ9qNPHPGRl5QJtChA3qI4',
    appId: '1:686258857713:android:b30821a332b7d50977ab50',
    messagingSenderId: '686258857713',
    projectId: 'hospital-4ad8b',
    storageBucket: 'hospital-4ad8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBEtO-OgI_MCefclKgbZtmT6AFvuZJGA',
    appId: '1:686258857713:ios:ee2807d1caa4f76a77ab50',
    messagingSenderId: '686258857713',
    projectId: 'hospital-4ad8b',
    storageBucket: 'hospital-4ad8b.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBEtO-OgI_MCefclKgbZtmT6AFvuZJGA',
    appId: '1:686258857713:ios:ee2807d1caa4f76a77ab50',
    messagingSenderId: '686258857713',
    projectId: 'hospital-4ad8b',
    storageBucket: 'hospital-4ad8b.appspot.com',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-hJiUQxc8ii_Z8jGAV6ujAKtvuQR3ay4',
    appId: '1:686258857713:web:33341514e5c8f53377ab50',
    messagingSenderId: '686258857713',
    projectId: 'hospital-4ad8b',
    authDomain: 'hospital-4ad8b.firebaseapp.com',
    storageBucket: 'hospital-4ad8b.appspot.com',
    measurementId: 'G-WVP2YK71Q2',
  );
}
